### ISSUE TITLE
not working on Xcode 7.3.1

### ISSUE THREAD

**Issue by codebreede** [recisio/AdaptiveSpaceItem#5]
moved the file AdaptiveSpaceItem.swift to my project and added a NSToolbaritem and set class AdaptiveSpaceItem but nothing happens and there is an error in the AdaptiveSpaceItem.swift file 

`self.timer = NSTimer.scheduledTimerWithTimeInterval(0.015, target: self, selector: "handleFadeTo", userInfo: nil, repeats: true)`

error says "No method declared with objective c selector 'handleFadeTo'"

**Comment by tbaranes** [comment]
Nice catch, that was due to a bad merge. I just fix it on master, could you try it again?
If everything ok, I will update the pod.

Thanks for the report 👍

**Comment by tbaranes** [comment]
Just released 1.0.1, CocoaPods will up to date in few minutes.
Closing this now, let me know if you have any issues!
